name: Deploy static site to Azure Web App

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_2BA461B78EC34CED959980E6053EA163 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_EF106A3854DA4BB484D57D729DDBD56F }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_54C5441371B5439386ECB5839197CAC4 }}

      - name: Deploy to Azure Web App
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'it4403-lab1-dedou'
          slot-name: 'Production'
          package: .

          
